name: Deploy Dev
on:
    push:
        branches:
            - deploy/dev
            - feature/github-actions-deploy

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            # TODO: Replace with short lived credentials
            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v2
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
                    aws-region: 'ap-southeast-2'

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    coverage: 'none'

            -   name: Install dependencies
                uses: ramsey/composer-install@v3
                with:
                    composer-options: '--no-interaction --no-progress --no-dev --no-suggest --no-scripts'

            -   name: Warmup Cache
                run: 'php bin/console cache:warmup -e dev'
                env:
                    APP_ENV: 'dev'

            -   name: Deploy
                run: |
                    cd aws-sam
                    sam deploy \
                        --no-confirm-changeset \
                        --stack-name serverless-base \
                        --resolve-s3 \
                        --capabilities CAPABILITY_IAM \
                        --region ap-southeast-2 \
                        --parameter-overrides ParameterKey=AppEnv,ParameterValue=dev ParameterKey=AppDebug,ParameterValue=1